services:
  - type: web
    name: remitos-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run deploy:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        sync: false
      - key: RUN_SEEDS
        value: false
      - key: RUN_MIGRATIONS
        value: true
    healthCheckPath: /estado
